import React from "react";
import { Button, Icon, useMediaQuery } from "@chakra-ui/react";
import { FaDownload } from "react-icons/fa";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface DownloadPdfButtonProps {
  transactions: any[];
  balance: number;
}

const DownloadPdfButton: React.FC<DownloadPdfButtonProps> = ({
  transactions,
  balance,
}) => {
  const handleDownloadPdf = () => {
    const doc = new jsPDF();

    // Add title and introductory text
    doc.setFontSize(16);
    doc.text("Financial Transactions Report", 10, 10);
    doc.setFontSize(12);
    doc.text(
      "This document provides a comprehensive overview of your recent financial transactions",
      10,
      20,
    );

    // Add balance information
    doc.setFontSize(14);
    doc.text("Current Account Balance:", 10, 35);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`$${balance.toFixed(2)}`, 10, 45);
    doc.setFont("helvetica", "normal");

    // Add transactions table
    const tableData = [
      ["Date", "Description", "Type", "Amount"],
      ...transactions.map((transaction) => [
        new Date(transaction.date).toLocaleDateString(),
        transaction.description,
        transaction.type,
        transaction.type === "INCOME"
          ? `+$${transaction.amount}`
          : `-$${transaction.amount}`,
      ]),
    ];

    autoTable(doc, {
      head: [tableData[0]],
      body: tableData.slice(1),
      startY: 55,
      styles: { fontSize: 10 },
      didParseCell: (data) => {
        if (data.column.index === 2) {
          // Column index for "Type"
          const cellText = data.cell.text.toString(); // Ensure text is a string
          if (cellText === "INCOME") {
            data.cell.styles.fillColor = [144, 238, 144]; // Light green
          } else if (cellText === "EXPENSE") {
            data.cell.styles.fillColor = [255, 182, 193]; // Light red (pink)
          }
        }
      },
    });

    // Add footer text
    doc.setFontSize(10);
    doc.text(
      "For any inquiries or further assistance, please contact our support team.",
      10,
      doc.internal.pageSize.getHeight() - 20,
    );
    doc.text(
      "Generated by: Alberto Junior",
      10,
      doc.internal.pageSize.getHeight() - 10,
    );

    doc.save("transactions_report.pdf");
  };

  // Responsive font size using Chakra UI's useMediaQuery hook
  const [isSmallScreen] = useMediaQuery("(max-width: 600px)");
  const fontSize = isSmallScreen ? "sm" : "md";

  return (
    <Button
      bg="black"
      border="1px solid #1a1a1d"
      color="white"
      borderRadius="10px"
      _hover={{ bg: "#0C0F15" }}
      _active={{ bg: "#1a1a1d" }}
      onClick={handleDownloadPdf}
      leftIcon={
        <Icon
          as={FaDownload}
          color="blue.500"
          boxSize={{ base: "16px", md: "20px", lg: "24px" }}
        />
      }
      size="lg"
      height={{ base: "60px", md: "75px", lg: "90px" }}
      width={{ base: "100px", md: "115px", lg: "130px" }}
      fontSize={{ base: "12px", md: "14px", lg: "16px" }}
    >
      Download PDF
    </Button>
  );
};

export default DownloadPdfButton;
